{% set name = "python-sscha" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-sscha-{{ version }}.tar.gz
  sha256: 484cf3215306d2b28bb4e2b01c9adccebc604a2323041d244624667bcdf74782

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - numpy
    - ase
    - scipy
    - cellconstructor
    - spglib
    - matplotlib-base
    - pip
    - libblas
    - liblapack
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - sscha
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mesonepigreco/python-sscha
  summary: Python implementation of the sscha code
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
