{% set name = "python-sscha" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 26364498bb1a21d42e504fdf688fea5a0d49cd5a55c0a6e5b9383983219db937

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - cmake
  host:
    - python
    - numpy
    - ase
    - scipy
    - cellconstructor
    - spglib
    - matplotlib-base
    - pip
    - libblas
    - liblapack
    - meson-python
  run:
    - ase
    - cellconstructor
    - matplotlib-base
    - scipy
    - spglib
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - sscha
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mesonepigreco/python-sscha
  summary: Python implementation of the sscha code
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
